language: python
python:
 - "3.5"
cache: pip
services:
  - postgresql
install:
 - pip install -r requirements.txt
 - pip install coveralls
before_script:
   - export APP_SETTINGS='testing'
   - export SECRET_KEY='thisisasecretkey'
   - export DB_NAME="test_dtb"
   - psql -c 'create database test_dtb;' -U postgres
script:
 - pytest app/test/v2/
after_success:
 - coveralls
  